modLoader="javafml"
loaderVersion="[32,)"
license="https://google.com"

[[mods]]
modId="omni"
version="${file.jarVersion}"
logoFile="logo.png"
displayName="Omni"
authors="Pugz"
credits=""
description='''A load of content covering all aspects of vanilla Minecraft.'''

[[dependencies.omni]]
modId="forge"
mandatory=true
versionRange="[32.0.72,)"
ordering="NONE"
side="BOTH"

[[dependencies.omni]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"