modLoader="javafml"
loaderVersion="[32,)"
license="https://github.com/c0d3break3r/Omni/blob/main/LICENSE"

[[mods]]
modId="omni"
version="${file.jarVersion}"
logoFile="logo.png"
displayName="Omni"
authors="Pugz"
credits=""
description='''Omni means '/of all things'/'''

[[dependencies.omni]]
modId="forge"
mandatory=true
versionRange="[34.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.omni]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"